name: 'Lock Threads'

on:

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    if: github.repository_owner == 'psf'
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v3
        with:
            issue-lock-inactive-days: 90
            pr-lock-inactive-days: 90